# Generated by Django 4.1.10 on 2023-08-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppDataModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images")),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("countOfVariables", models.IntegerField()),
                ("variables", models.JSONField()),
                ("formula", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="OutputPageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images")),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("countOfVariables", models.IntegerField()),
                ("variables", models.JSONField()),
            ],
        ),
    ]
