# Generated by Django 4.1.10 on 2023-08-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculation_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appdatamodel",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="outputpagemodel",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
